### ISSUE TITLE
ability to pass the timestamp via API?

### ISSUE THREAD

**Issue by Candrom87** [vontainment/v-gpt-qdrant-api#11]
I think it would be a good idea to be able to pass the timestamp via API. This way the memories can be stored with the users actual timezone, instead of the hard-coded UTC timezone.

**Comment by vontainment** [comment]
This is a selfhosted solution, your server should be set to your time-zone.

**Comment by vontainment** [comment]
Though i have considerd having the datetime at that moment returned with results so the ai can compare newer vs older entries

**Comment by Candrom87** [comment]
But the timestamp should be associated to the user and it’s memory, not to a server location. If users are outside this timezone, the memories have the wronge timestamp for the users, see what I mean?

**Comment by vontainment** [comment]
The issue is the AI will not know the time and date to fill it in.

**Comment by vontainment** [comment]
The date time is more for chronology.  I tell it i hate icecream and the n 3 months later tell it i love icecream. and then asked it how i feel about icecream it will now see i used to hate it but now love it. Because no matter the timezone the timeline is accurate. The AI's don't know even remotely what day, time or year it is. So as a GPT action this won't work at all. and it would requier custoi mods for each framework it is used with. one possible solution is to add a timezone field. set it as optional and tell the ai your timezone or just tell it to recalculate time timezone to a different one. The AI does not know the current time so having it in your timezone dose not bring anything ir really is only for a timeline of what was remembered first as newer memories would be considered correct over oldetr.

**Comment by Candrom87** [comment]
I know that GPTs don’t have the correct time and date. 

Let me give you an example of what I’m currently doing. I built a client that passes the actual time and date to the gpt, with the user’s session. 
I use the memory for several different things, including the usual long-term memory that you just described, but I also allow the users to set up reminders and recurring tasks for the GPT to execute, and this is exactly where accurate date/time of the user comes into play.
Right now I have workarounds for the GPT to calculate differences, but it would me much simpler if there was an option to just pass the user’s date/time as timestamp for the vector to save.

**Comment by vontainment** [comment]
You built a custom client.. that client would need to pass the the datatime. this is something you would need to fork the repo here and change the code to fit your needs. This is meant as a universal api for many frameworks and gpts. The change you want to make this only work for your client. So you need to take this and change it to work with your custom client.
