### ISSUE TITLE
Possibility to add update_memory endpoint?

### ISSUE THREAD

**Issue by Candrom87** [vontainment/v-gpt-qdrant-api#9]
Would it be possible to add a "update_memory" endpoint? I'd like an agent to be able to update a memory, maybe add tags even. This would make it possible to evolve a memory.

Example: user tells agent about some unresolved matter.. but the next day the matter has been resolved by the user.. now in the current system there are 2 memories, one about the matter being unresolved and another being the resolved matter. This more often than not confuses the AI. It'd be great to add to or simply rewrite the existing matching memory without having to let the agent find, delete existing and create new memory (deleting and re-creating would also mess with the original timestamp of the memory, which we need to preserve in my opinion).

**Comment by vontainment** [comment]
witch version are you using? The dev branch has a lightweight embedding model built in and the ability to delete and recreate memories.

**Comment by vontainment** [comment]
The timestamp would let the AI know which memory is newest. updatring them in general would nto be reflective of real memory as opinions change. if you like icecream then ahte it the current system would show that change.

**Comment by Candrom87** [comment]
I do use the dev version.

I currently have set up different functions for the agent to execute, recall, save and forget. It would be much simpler, for my particular use-case to have the memory-api allow to overwrite/update a vector instead of having the gpt to first recall to get the uuid, then delete and write a new vector. 

It could work like this: the gpt searches for the memory to update, passes that uuid plus an update command to the api including the updated memory. The api would then do the rest.

**Comment by vontainment** [comment]
that is the issue, you can't delete without the uuid. A memory has to be recalled to be deleted. or you have to go into the vector database gui and delete change. To edit an entry in any database you have to have some kind of ID to get the entry. so once you have the uuid you can delete a memory if you want and add a new one. The AI's should be-able to do both in one round. but that is not an efficient way, that's why there are timestamps on entries. if you give it info it will always take the newest timestamp as true at that moment. So if you save you like icecream and then save i hate icecream the ai would know you liked icecream but now dislike it, Just like real memory. The issue is trying to keep the amount of tools to a minimal so it doesn't take up all the slots for tools. The tool is suppose to be automatic. but any deletions would need to be manual. vector databases and AIs don't interact in a way that would allow the AI to easily overwrite entries. It can't be sure that what it saves is not already there as the AIs can not ingest the whole database. Thats why it uses the timestamp to know a valid updtodate entry when entries contradict.
